--- #YAML:1.0
name:                Text-Unaccent-PurePerl
version:             0.01
abstract:            remove accents from a string
license:             ~
author:              
    - Peter J. Acklam <pjacklam@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
